### ISSUE TITLE
Commenting a line starting with a link inserts the comment into the link

### ISSUE THREAD

**Issue by mohkale** [tarsius/orglink#11]
When you have `(setq orglink-match-anywhere t)` enabled and try to comment a line beginning with an org-link, the inside of the link description ends up commented instead of the link itself.

For example say I have a scratch buffer like this:

```
;; This buffer is for text that is not saved, and for Lisp evaluation.
;; To create a file, visit it with SPC f f and enter text in its buffer.

[[file:foo.html][blarg]]
```

On the last line if I run `M-: (comment-region (line-beginning-position) (line-end-position))` I end up with 

```
;; This buffer is for text that is not saved, and for Lisp evaluation.
;; To create a file, visit it with SPC f f and enter text in its buffer.

[[file:foo.html][;; blarg]]
```

Is there a way to fix this?

**Comment by tarsius** [comment]
I can reproduce this issue also when using a mode such as `text-mode`. It appears that the `orglink` implementation has a bug that the `org` implementation doesn't have. I noticed that the `org` implementation has significantly changed since I copied and adjusted it, likely also to fix this bug. I should copy and adjust again to take advantage of the improvements. Doing that might take a little bit longer.

**Comment by mohkale** [comment]
@tarsius 

Thanks for looking into the issue. Truth be told while annoying I don't think its a major issue. I checked after installing this plugin but org-link-minor-mode has the same issue and in all my time using it I'd never encountered it before experimenting with this plugin. I think its safe to say this isn't a deal braker, so I'm fine with a wontfix resolution for now. I might send an issue on the mailing list if I encounter it more or run into a similair situation with another plugin.

Once again, thank you.
