### ISSUE TITLE
The future of orglink

### ISSUE THREAD

**Issue by michael-heerdegen** [tarsius/orglink#5]
Hi,

since org is one of very few ways to get hyperlinks in any arbitrary buffer (linkd.el is another, but not so widespread), and org is part of Emacs, this package IMHO should consequently become a part of org.  I think many Emacs users unsuccessfully search for the feature this package offers in vanilla Emacs/org.  Just my personal opinion,of course.

**Comment by tarsius** [comment]
I've decided to not attempt to add this to Org itself because I don't think that doing so would actually help users, and it would make it harder for me (I would have to follow their workflow etc.) as well as them (it would be one more library they would have to care for).

In particular I don't think that adding this to Org would make `orglink` more discoverable, quite the opposite actually. As it stands it at least appears in the output `list-packages`. As the maintainer of the Emacsmirror I surprisingly often have to tell the author of a new Org extensions that what s/he just wrote already exists in Org's `contrib/` directory. If some users spend hours or even days writing a new library without first checking if Org already provides an implementation, then I expect that among the users who wouldn't go as to write it themselves, there also are quite a few who forget checking Org itself for Org extensions.

**Comment by michael-heerdegen** [comment]
Ok, thanks anyway.
