### ISSUE TITLE
cond: Symbol’s value as variable is void: org-link-descriptive

### ISSUE THREAD

**Issue by 717g301github** [tarsius/orglink#6]
GNU Emacs 27.0.50 (build 3, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)
     of 2019-08-04

    command-execute: Buffer is read-only: #<buffer *Messages*>
    Mark activated
    Error during redisplay: (jit-lock-function 21) signaled (void-variable org-link-bracket-re) [17 times]
    Error during redisplay: (jit-lock-function 100) signaled (void-variable org-link-bracket-re)
    Error during redisplay: (jit-lock-function 115) signaled (void-variable org-link-bracket-re)

**Comment by tarsius** [comment]
Thinking that that had already been released I recently changed `orglink` to depend on version 9.3 of `org`. Sorry about that.

However this only affects the development version of `orglink`, so you have two choices:

1. Use the latest release of both `org` and `orglink`, or
2. Use development version of both `org` and `orglink`.

I don't think that any elpa archive distributes snapshots of `org` (but might be wrong), which makes it hard to do (2). In order to use the stable version of `orglink` you have to add the `melpa-stable` archive and then pin `orglink` to that archive (see `package-pinned-packages`).

**Comment by 717g301github** [comment]
* Jonas Bernoulli <notifications@github.com> [2019-08-08 12:15]:
> Thinking that that had already been released I recently changed
> `orglink` to depend on version 9.3 of `org`. Sorry about that.

Well. I have Org version 9.2.5 and I will wait until it gets
downloadable from repositories.

> However this only affects the development version of `orglink`, so you have two choices:
> 
> 1. Use the latest release of both `org` and `orglink`, or

I don't know what is latest release. I am upgrading from elpa I guess.

> I don't think that any elpa archive distributes snapshots of `org`
> (but might be wrong), which makes it hard to do (2). In order to use
> the stable version of `orglink` you have to add the `melpa-stable`
> archive and then pin `orglink` to that archive (see
> `package-pinned-packages`).

Aha

**Comment by analyticd** [comment]
Yeah, this same error blew up for me today when I updated my elpa/melpa packages which include org and orglink. Glad I found this ticket.

**Comment by codygman** [comment]
> Use the latest release of both org and orglink, or

I use straight.el to manage packages, so I guess I can probably do this option. I'll post back with a code snippet once I verify it works.
