### ISSUE TITLE
orglink mode makes buffer readonly

### ISSUE THREAD

**Issue by symbiont-matthew-piziak** [tarsius/orglink#7]
I can't find it `orglink.el`, but in my experience when I activated `orglink-mode` in a LUI-derived major-mode buffer it makes it readonly. Do you know what this might be about?

**Comment by symbiont-matthew-piziak** [comment]
Wow, this happens when I use `org-link-minor-mode`, too!

**Comment by symbiont-matthew-piziak** [comment]
I ended up simply adding `org-open-at-point-global` to my mode map, eschewing the fontification for now.

**Comment by tarsius** [comment]
`orglink` uses font-lock and `lui` does not. That is problematic because the text-properties set using font-lock will mess with those set by some other method and vice versa. (It is a bit surprising that these affects whether text is editable and not just messes with faces. I am guessing that this does not affect whether the whole buffer is editable but the `read-only` property of certain text.)

Generally speaking, this can be made to work, but is a burden on the non-font-lock major-mode. (We have recently done that for Magit (https://github.com/magit/magit/pull/3886), but I am still not sure this was the right move.)

So I don't this can be made without making invasive changes to lui, which IMO are not justified by the importance of the feature doing so would enable.

**Comment by matthew-piziak** [comment]
Fair enough, thanks @tarsius.
