### ISSUE TITLE
Cannot open load file: Datei oder Verzeichnis nicht gefunden, dash

### ISSUE THREAD

**Issue by 717g301github** [tarsius/orglink#9]
```
Compiling orglink.el

In toplevel form:
orglink.el:53:1:Error: Cannot open load file: Datei oder Verzeichnis nicht gefunden, dash
make: *** [Makefile:30: orglink.elc] Fehler 1
```

**Comment by tarsius** [comment]
`dash` is a dependency of `orglink`.

You have to install `dash` in order to use `orglink`. I recommend you install packages using Emacs' built-in package manager. You need to configure the package manager to also use the Melpa package archive, which distributes both packages. If you install `orglink` like this, then doing so should also automatically install `dash`.

**Comment by 717g301github** [comment]
I have dash and loaded. It is not recognized.

**Comment by tarsius** [comment]
That error message says you don't. Try restarting Emacs. If that doesn't help, try reinstalling `dash`.

**Comment by 717g301github** [comment]
I have dash. And loaded.

The error appears when running make in directory.

**Comment by tarsius** [comment]
Ah, I overlooked that you were using `make` to build the package. The problem is that while you have `dash` the Makfile does not know where it is. If you look at the Makefile, then you will see that it assume that all dependencies are installed at `../DEPENDENCY` relative to where `orglink` itself installed. If you know a bit of `make` syntax, then you can also deduce that if that is not the case you have the option to set the `LOAD_PATH` in `.config.mk` instead.

**Comment by 717g301github** [comment]
If dash is loaded from elpa, then it looks something like this:
DEPS  = dash-20190920.1035

so by changing that, and having orglink in ~/.emacs.d/elpa/orglink/ then I could run make. Then again I have problems, which I do not understand, so you work with the development version of Org?

```
Compiling orglink.el

In orglink-mode:
orglink.el:136:32:Warning: reference to free variable ‘org-link-descriptive’
orglink.el:136:32:Warning: assignment to free variable ‘org-link-descriptive’

In orglink-activate-bracket-links:
orglink.el:173:33:Warning: reference to free variable ‘org-link-bracket-re’

In orglink-activate-angle-links:
orglink.el:208:33:Warning: reference to free variable ‘org-link-angle-re’

In orglink-activate-plain-links:
orglink.el:221:33:Warning: reference to free variable ‘org-link-plain-re’
Generating orglink-autoloads.el
  INFO     Scraping files for orglink-autoloads.el... 
  INFO     Scraping files for orglink-autoloads.el...done

```

**Comment by tarsius** [comment]
> so by changing that

Am not sure what you did, but glad it works for you now.

> so you work with the development version of Org?

Yes. And you already opened another issue about the issues that this is causing you #8. That issue is a duplicate of #6, to which I pointed you and which explains how to deal with this.
